### ISSUE TITLE
Add this awesome list to https://github.com/sindresorhus/awesome#readme

### ISSUE THREAD

**Issue by hhkaos** [Esri/awesome-arcgis-developers#26]
I think we should add this repo to https://github.com/sindresorhus/awesome#readme. I would add it under `#Platforms`.

Which description should we use? Something like this?

> - [ArcGIS Platform](https://github.com/Esri/awesome-arcgis-developer) - Platform as a Service (PaaS) for mapping applications that contain ready-to-use location services, data hosting, and content management services, but also include tools and APIs to interact and consume them.

cc: @alaframboise @jf990 @ak-kemp

**Comment by jf990** [comment]
Suggestion:

* [ArcGIS Platform](https://developers.arcgis.com/) - Esri's Platform as a Service (PaaS) for mapping and location analysis applications with ready-to-use location services, data hosting, APIs, tools, and content management services.

**Comment by hhkaos** [comment]
I noticed you changed the URL. That repo only accept links to other awesome lists.

Reading [the guidelines](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md#requirements-for-your-awesome-list) again I just realized there are a couple of requirements we don't meet:

> - Has an appropriate license.
> 	- **We strongly recommend the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/), but any [Creative Commons license](https://creativecommons.org/choose/) will work.**
> 		- Tip: You can quickly add it to your repo by going to this URL: `https://github.com/<user>/<repo>/community/license/new?branch=main&template=cc0-1.0` (replace `<user>` and `<repo>` accordingly).
> 	- **A code license like MIT, BSD, Apache, GPL, etc, is not acceptable**. Neither are WTFPL and [Unlicense](https://unlicense.org).
> 	- Place a file named `license` or `LICENSE` in the repo root with the license text.
> 	- **Do not** add the license name, text, or a `Licence` section to the readme. GitHub already shows the license name and link to the full text at the top of the repo.
> 	- To verify that you've read all the guidelines, please comment on your pull request with just the word `unicorn`.
> - All non-important but necessary content (like extra copyright notices, hyperlinks to sources, pointers to expansive content, etc) should be grouped in a `Footnotes` section at the bottom of the readme. The section should not be present in the Table of Contents.

So:

* Our Apache License is not valid.
* And I think they will request us to rename "Licensing" for "Footnotes"

But I'm asking permission from our admins to do so, but I haven't received it. They need to talk about it in the next admin meeting :)

**Comment by jf990** [comment]
@hhkaos regarding the URL change, I didn't understand the purpose, so we should change it to this repo.
