### ISSUE TITLE
ArcGIS CityEngine SDKs

### ISSUE THREAD

**Issue by mistafunk** [Esri/awesome-arcgis-developers#38]
Hi, great list.

Would you mind adding the CityEngine procedural modeling SDK?
https://esri.github.io/cityengine

This link points to our C++ and Python APIs to create 3d building models out of GIS features:
* C++: https://github.com/esri/cityengine-sdk
* Python: https://github.com/Esri/pyprt
* Python Examples: https://github.com/Esri/pyprt-examples

**Comment by hhkaos** [comment]
Thank you Simon!. At the beginnig the idea was to focus on resources for regular developers with no GIS/ArcGIS knowledge, but I realized that even myself commited Arcpy, Enterprise SDK, etc. Now I think the name of the repo is quite generic, so I think I would recommend to split it in two different lists, an awesome-arcgis-platform (this one) and awesome-arcgis-developer. What do you think @jf990 ?

**Comment by jf990** [comment]
@hhkaos I think it is fair to include any resource that would help any developer of any level, as long as we organize the links into categories that make it clear the purpose and audience.

**Comment by hhkaos** [comment]
sorry for the huge delay... done 😅

**Comment by mistafunk** [comment]
Nice, good things take time ;-)
